name = "Craftpunk Modpack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "67db7b7ee5602c08b922ff5501ee29ee9b92cadcd42186256169533dcbcf67c9"

[versions]
forge = "47.1.43"
minecraft = "1.20.1"
